server:
  port: 8090

spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: product_user
#    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    logging:
      level:
        org.hibernate: INFO


